core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("product/", include("product.urls"))
]

core/product/urls.py
from django.urls import path
from . import views


app_name = "blog"

urlpatterns = [
    path("list/", views.list_view, name="list"),
    path("create/", views.create_view, name="create"),
    path("detail/<id>/", views.detail_view, name="detail"),
    path("update/<id>/", views.update_blog_view, name="update"),

]

core/product/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author_name = models.CharField(max_length=255)

    def __str__(self):
        return self.title

core/product/forms.py
from django import forms
from .models import Blog


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'content', 'author_name')

core/product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Blog
from .forms import BlogForm


def list_view(request):
    context = {
        "blogs": Blog.objects.all(),
    }
    return render(request, "list.html", context)


def create_view(request):

    form = BlogForm()

    if request.method == "POST":
        form = BlogForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("blog:list")

    context = {
        "form": form,
    }
    return render(request, "create.html", context)


def update_blog_view(request, id):
    blog = get_object_or_404(Blog, id=id)
    form = BlogForm(instance=blog)

    if request.method == "POST":
        form = BlogForm(request.POST, instance=blog)
        if form.is_valid():
            form.save()

            return redirect("blog:list")
    context = {
        "form": form
    }
    return render(request, "update.html", context)


def detail_view(request, id):
    blogs = Blog.objects.get(id=id)
    context = {
        "id": id,
        "blogs": blogs
    }
    return render(request, "detail.html", context)

core/product/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Bootstrap demo</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Logo</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </nav>

    <!-- Navbar -->

    {% block content %} {% endblock %} {% block body %} {% endblock %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

core/product/templates/create.html
{% extends "base.html" %} {% block body %}
<form method="POST" class="my-form">
  {% csrf_token %} {{form.as_p}}
  <button type="submit" class="my-button btn btn-primary">Submit</button>
</form>

{% endblock %}

core/product/templates/detail.html
{% extends "base.html" %} {% block body %}

<h1>Title: {{blogs.title}}</h1>

<h4>Content: {{blogs.content}}</h4>

<p>Author_name: {{blogs.author_name}}</p>

<p>Created at: {{blogs.created_at}}</p>
<p>Updated at: {{blogs.updated_at}}</p>

{% endblock %}

core/product/templates/list.html
{% extends "base.html" %} {% block body %}
<h1>Blog List</h1>

<ul>
  {% for blog in blogs %}
  <li>
    <a href="{% url 'blog:detail' blog.id %}">{{blog.title}} </a>
    -- {{blog.content}}
    <br />
    {{blog.author_name }}
  </li>
  {% endfor %}
</ul>

{% endblock %}

core/product/templates/update.html
{% extends "base.html" %} {% block body %}
<form method="POST" class="my-form">
  {% csrf_token %}{{form.as_p}}
  <button type="submit" class="my-button btn btn-primary">Submit</button>
</form>

{% endblock %}